[package]
name = "pgn-parser"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.0.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
indicatif = "0.17.5"
